### ISSUE TITLE
Header (Componente Vue)

### ISSUE THREAD

**Issue by Ghangaz** [PlanificacionViaje/PlanificacioFrontEnd#5]

**Comment by RaulHinojosa24** [comment]
Holii, una cosita, el componente debería quedarse siempre visible arriba, aun que le hagas scroll? (porque ahora mismo no lo hace)
Y también, se podría hacer ya un poco de lógica, tener una variable que te diga si el usuario ha iniciado sesión y en función de eso, te muestre el icono del perfil o un botón de login/registro :3
